server:
  port: 8081
spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test?autoReconnect=true&userSSL=false
    username: admin
    password: 1q2w3e4r
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test?autoReconnect=true&userSSL=false
    username: admin
    password: 1q2w3e4r

